[options]
admin_passwd = $pbkdf2-sha512$600000$nJOSUurdm3OuVap17n1vLQ$CnmpukRZ3p.cry.Ep29mDc4A9P6/NZ.H5KPB.k8NDSrTB/aL4Tu3v8xVC8oOYi1cGSqtxFIxZ0ViRk/DKHId3w
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
dev_mode = reload
log_level = info
logfile = /dev/stdout
workers = 0
max_cron_threads = 1
watchdog_enable = True
proxy_mode = True

